/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import nutricionista.modelos.Comida;
import nutricionista.modelos.ComidaData;
import nutricionista.modelos.Conexion;
import nutricionista.modelos.Dieta;
import nutricionista.modelos.DietaComida;
import nutricionista.modelos.DietaComidaData;
import nutricionista.modelos.DietaComidaPacienteComida;
import nutricionista.modelos.DietaData;

/**
 *
 * @author RealEnvido
 */
public class DietaComidaF extends javax.swing.JInternalFrame {
private DefaultTableModel modelo;
private ComidaData cd;
    /**
     * Creates new form DietaComidaF
     */
    public DietaComidaF() {
    try {
        initComponents();
        Conexion con = new Conexion();
        cd = new ComidaData(con);
        modelo = new DefaultTableModel();
        armarCabezeraTabla();
        List<Comida> lista = cd.obtenerTodasLasComidas();
        for(Comida it:lista){
           CBcomidas.addItem(it.getNombre());
            
        }
        CBcomidas.setSelectedItem(null);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(DietaComidaF.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CBcomidas = new javax.swing.JComboBox<>();
        TFnombre = new javax.swing.JTextField();
        TFcalorias = new javax.swing.JTextField();
        TFdetalles = new javax.swing.JTextField();
        TFsumaCalorias = new javax.swing.JTextField();
        BsumaCalorias = new javax.swing.JButton();
        Bagregar = new javax.swing.JButton();
        TFdni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTresutadosDietaComida = new javax.swing.JTable();
        Bbuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LidDieta = new javax.swing.JLabel();
        TFborrarNombre = new javax.swing.JTextField();
        BborrarCalorias = new javax.swing.JTextField();
        BborrarDetalles = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        TFborrarId = new javax.swing.JTextField();

        CBcomidas.setMaximumRowCount(100);
        CBcomidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBcomidasActionPerformed(evt);
            }
        });

        TFnombre.setEditable(false);
        TFnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnombreActionPerformed(evt);
            }
        });

        TFcalorias.setEditable(false);

        TFdetalles.setEditable(false);

        TFsumaCalorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFsumaCaloriasActionPerformed(evt);
            }
        });

        BsumaCalorias.setText("Sumar Calorias de la Dieta");
        BsumaCalorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsumaCaloriasActionPerformed(evt);
            }
        });

        Bagregar.setText("Agregar Comida");
        Bagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagregarActionPerformed(evt);
            }
        });

        TFdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFdniActionPerformed(evt);
            }
        });

        jLabel1.setText("NOMBRE DE PACIENTE:");

        JTresutadosDietaComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTresutadosDietaComida);

        Bbuscar.setText("BUSCAR");
        Bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("ID de Dieta");

        BborrarCalorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BborrarCaloriasActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(CBcomidas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(TFcalorias))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFdni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LidDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Bbuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(Bagregar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TFborrarId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFborrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BborrarCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BborrarDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BsumaCalorias)
                .addGap(18, 18, 18)
                .addComponent(TFsumaCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TFdetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Bbuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LidDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFcalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBcomidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bagregar))
                .addGap(18, 18, 18)
                .addComponent(TFdetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BsumaCalorias)
                    .addComponent(TFsumaCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFborrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BborrarCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BborrarDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(TFborrarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFdniActionPerformed
        
    }//GEN-LAST:event_TFdniActionPerformed

    private void BbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuscarActionPerformed
    try {
        borrarFilas();
        Conexion con = new Conexion();
        DietaComidaData dcd = new DietaComidaData(con);
        List<DietaComidaPacienteComida> dietas = null;
        dietas = dcd.buscarDietaComidaPorPaciente6(TFdni.getText());
      
        for(DietaComidaPacienteComida m:dietas){
            LidDieta.setText(Integer.toString(m.getIdDieta()));
           modelo.addRow(new Object[]{m.getIdDieta(),m.getIdComida(),m.getNombreComida(),m.getCalorias(),m.getDetalles()});
            //System.out.println(m.getNombreComida());
          }  
       
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(DietaComidaF.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BbuscarActionPerformed

    private void CBcomidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBcomidasActionPerformed
       if(CBcomidas.getSelectedItem() != null)
       {
           try {
               Conexion con = new Conexion();
               ComidaData cc = new ComidaData(con);
               TFnombre.setText(CBcomidas.getSelectedItem().toString());
               TFcalorias.setText(Double.toString(cc.buscarComidaPorNombre(CBcomidas.getSelectedItem().toString()).getCalorias()));
               TFdetalles.setText(cc.buscarComidaPorNombre(CBcomidas.getSelectedItem().toString()).getDetalle());
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(DietaComidaF.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       else{
        TFnombre.setText(null);
        TFcalorias.setText(null);
        TFdetalles.setText(null);
       }
    }//GEN-LAST:event_CBcomidasActionPerformed

    private void TFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnombreActionPerformed

    private void BagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagregarActionPerformed
    try {
        Conexion con = new Conexion();
        DietaComidaData dcd = new DietaComidaData(con);
        ComidaData cc = new ComidaData(con);
        DietaData dd = new DietaData(con);
        Dieta dieta = new Dieta();
        Comida comida = new Comida();
        DietaComida dietacomida = new DietaComida();
        
        dieta = dd.buscarDieta(Integer.parseInt(LidDieta.getText()));
        comida = cd.buscarComidaPorNombre(TFnombre.getText());
        dietacomida.setIdDieta(dieta.getId());
        dietacomida.setIdComida(comida.getId());
        dcd.guardarDietaComida(dietacomida);
        
        BbuscarActionPerformed(evt);
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(DietaComidaF.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BagregarActionPerformed

    private void TFsumaCaloriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFsumaCaloriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFsumaCaloriasActionPerformed

    private void BsumaCaloriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsumaCaloriasActionPerformed
    try {
        Conexion con = new Conexion();
        DietaData dd = new DietaData(con);
        ComidaData cd = new ComidaData(con);
        List <Comida> listaSumarCalorias;
        int caloriasTotales = 0;
        listaSumarCalorias = dd.CantidadCaloriasDieta2(Integer.parseInt((LidDieta.getText())));
        caloriasTotales = cd.sumaDeCaloriasComidas(listaSumarCalorias);
        TFsumaCalorias.setText(Integer.toString(caloriasTotales));
       
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(DietaComidaF.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BsumaCaloriasActionPerformed

    private void BborrarCaloriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BborrarCaloriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BborrarCaloriasActionPerformed
     public void armarCabezeraTabla()
    {
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("idDieta");
        columnas.add("idPaciente");
        columnas.add("Comida");
        columnas.add("Calorias");
        columnas.add("Detalles");
         for(Object it:columnas)
         {
            modelo.addColumn(it);
            
         }
         JTresutadosDietaComida.setModel(modelo);
    }
      public void borrarFilas()
     {
     int a = modelo.getRowCount()-1;
      for(int i = a;i>=0;i--){
      modelo.removeRow(i);
      }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bagregar;
    private javax.swing.JTextField BborrarCalorias;
    private javax.swing.JTextField BborrarDetalles;
    private javax.swing.JButton Bbuscar;
    private javax.swing.JButton BsumaCalorias;
    private javax.swing.JComboBox<String> CBcomidas;
    private javax.swing.JTable JTresutadosDietaComida;
    private javax.swing.JLabel LidDieta;
    private javax.swing.JTextField TFborrarId;
    private javax.swing.JTextField TFborrarNombre;
    private javax.swing.JTextField TFcalorias;
    private javax.swing.JTextField TFdetalles;
    private javax.swing.JTextField TFdni;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JTextField TFsumaCalorias;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
